[workspace]
members = ["packages/contracts/starkwars"]

[workspace.dependencies]
starknet = "2.9.1"

[workspace.dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.34.0" }
assert_macros = "2.9.1"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
